In [37]:
import tensorflow as tf
import numpy as np

In [61]:
model = tf.keras.models.load_model("best_model")

In [62]:
model.summary()

Model: "sequential_38"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_76 (Conv2D)          (None, 64, 64, 24)        672       
                                                                 
 max_pooling2d_76 (MaxPoolin  (None, 16, 16, 24)       0         
 g2D)                                                            
                                                                 
 conv2d_77 (Conv2D)          (None, 16, 16, 16)        3472      
                                                                 
 max_pooling2d_77 (MaxPoolin  (None, 8, 8, 16)         0         
 g2D)                                                            
                                                                 
 flatten_38 (Flatten)        (None, 1024)              0         
                                                                 
 dense_76 (Dense)            (None, 36)              

In [63]:
def load_and_predict(img_path: str):
    # Loading the image.
    img = tf.keras.utils.load_img(img_path)

    # pre processing the image.
    size=(64, 64)

    img = tf.image.resize(sunny, size)
    img = img[None,...]

    # predicting the img.
    prediction = model.predict(img)

    return prediction

In [68]:
rainy_model = load_and_predict("sunny.jpg")

1/1 [==============================] - 0s 30ms/step


In [69]:
rainy_model

array([[0., 0., 1.]], dtype=float32)

In [66]:
rainy_model

array([[0., 0., 1.]], dtype=float32)

In [67]:
cloudy_model

array([[0., 0., 1.]], dtype=float32)