## Array Operations

Arrays are designed to support fast computation and comparisons. The most common types of operations are:

- Between arrays and scalars (one value at a time)
- Universal functions (np.function_name)
  - Unary (performed on a single array): abs, sqrt, ceil, floor.
  - Binary (performed between two arrays): +, -, <, and, etc.
- Mathematical and Statistical Functions.
  - Aggregation: mean, sum, std, variance, min/max, etc.
  - Non-aggregation: cumsum, cumprod

In [2]:
import numpy as np

### Broadcasting

You can add a scalar value to an array, which will add the scalar as if it were an array.

In [8]:
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
arr1

array([[2, 3, 4],
       [5, 6, 7]])

In [9]:
arr1 += 1
arr1

array([[3, 4, 5],
       [6, 7, 8]])

An array can also be a part of the broadcast if the sizes are compatible.

In [10]:
arr2 = np.array([[2, 3, 4], [5, 6, 7]])
arr2

array([[2, 3, 4],
       [5, 6, 7]])

In [11]:
arr1 + arr2

array([[ 5,  7,  9],
       [11, 13, 15]])

### Comparison

A comparison can take place with a scalar.

In [12]:
arr3 = np.array([[2, 3, 4], [5, 6, 7]])
arr3

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
arr3 == 3

array([[False,  True, False],
       [False, False, False]])