### Array vs. Lists

Arrays may seen similar to lists (e.g they both are mutable and iterable sequences), but they are distinct data structures. \
Use an array whenever you are performing any large scale computations or comparisons.

However, lists do not have restrictions on the size of nested sequences, whereas arrays have restrictions for constructing \
a useful form object.

In [2]:
import numpy as np

In [5]:
# Example - Cannot create a "holey" array.
arr1 = np.array(
[
    [1, 2, 3],
    [3, 4, 5]
]
)

In [6]:
arr1

array([[1, 2, 3],
       [3, 4, 5]])

### Execution Time

__Using %timeit to check the time for executing cell, we can see the length of the time of creation of a list vs. an array__

Example %timeit -r5 -n10000
r = number of times to repeat the timer.
n = number of times to execute the statement.

In [7]:
import random

#### List Creation

In [8]:
%timeit -r5 -n100 list1 = [random.randrange(1, 51) for i in range(600)]

3.17 ms ± 908 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)


#### Array creation

In [9]:
%timeit -r5 -n100 arr1 = np.random.randint(1, 51, 600)

87.7 µs ± 48.6 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)


### Indexing and Slicing

Array indexing and slicing are similar to lists.

In [11]:
arr1 = np.array([6, 7, 2, 8, 7, 5])

In [14]:
arr1[2:4]

array([2, 8])

List rely on deep copy, while arrays rely on a shallow copy.
- Any changes to a list slice are not reflected in the original list.
- Any changes to an array slice are reflected in the original array

In [15]:
list1 = list(range(6))

In [16]:
list1

[0, 1, 2, 3, 4, 5]

In [17]:
list_slice = list1[1:4]
list_slice

[1, 2, 3]

In [18]:
list_slice[0] = -1

In [19]:
list_slice

[-1, 2, 3]

In [20]:
list1

[0, 1, 2, 3, 4, 5]

In [21]:
arr1

array([6, 7, 2, 8, 7, 5])

In [22]:
arr2 = arr1[1:4]

In [24]:
arr2[2] = 4
arr2

array([7, 2, 4])

In [25]:
arr1

array([6, 7, 2, 4, 7, 5])

## Shallow vs. Deep copy

In [26]:
old_list = [1, 2, 3, 4, 5]

In [27]:
id(old_list)

1580714610240

In [28]:
new_list = old_list

In [31]:
old_list.append(6)
old_list

[1, 2, 3, 4, 5, 6]

In [35]:
new_list[1:4] = [1 ,3 ,5]
new_list

[1, 1, 3, 5, 5, 6]

In [36]:
old_list

[1, 1, 3, 5, 5, 6]

In [37]:
new_list

[1, 1, 3, 5, 5, 6]

In [38]:
import copy

In [39]:
new_deep_list = copy.deepcopy(old_list)
new_deep_list

[1, 1, 3, 5, 5, 6]

In [43]:
new_deep_list[3:4] = [3, 5, 6, 7]

In [44]:
new_deep_list

[1, 1, 3, 3, 5, 6, 7, 5, 6]

In [45]:
old_list

[1, 1, 3, 5, 5, 6]