### Boolean Data for Data Analysis

Boolean arrays can be used to learn about the data.

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [5]:
(arr1 % 2 == 0).sum()

5

In [7]:
 (arr1 < 5).any()

True

In [8]:
(arr1 < 0).any()

False

In [9]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
 (arr1 < 5).all()

False