## Common Array attributes

- `ndim`: number of dimensions in the Array.
- `shape`: number of dimensions in the Array.
- `dtype`: data type of values in the Array.
- `size`: total number of values in the array.

In [2]:
import numpy as np

In [3]:
arr1 = np.random.rand(3, 5)
arr1

array([[0.21987964, 0.52276042, 0.41350833, 0.00623143, 0.85071394],
       [0.90711916, 0.21647302, 0.33239822, 0.44574167, 0.56934896],
       [0.6223843 , 0.37215792, 0.23443189, 0.57397503, 0.2649959 ]])

In [5]:
print(f"Number of Dimensions: {arr1.ndim}")

Number of Dimensions: 2


In [6]:
print(f"Shape of array: {arr1.shape}")

Shape of array: (3, 5)


In [7]:
print(f"Data type of array: {arr1.dtype}")

Data type of array: float64


In [8]:
print(f"Size of array: {arr1.size}")

Size of array: 15


## Using `astype` to convert the dtype of array.

In [10]:
arr1 = arr1.astype(int)

In [11]:
arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
arr = arr1.astype(float)

In [13]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr1 = np.random.rand(2, 5)
arr1.size

10

In [15]:
arr2 = np.array([10.7, 3.2, 5.8, 11.3])

In [16]:
arr2.astype(int)

array([10,  3,  5, 11])