## Creating 2 dimensional array.
Specify two dimensions (rows and columns)

In [2]:
import numpy as np

In [3]:
arr1 = np.random.rand(4, 3)
arr1

array([[0.41560478, 0.7699988 , 0.64323857],
       [0.92447719, 0.83659771, 0.46094167],
       [0.53524803, 0.23581939, 0.19431428],
       [0.89207446, 0.28165516, 0.83223626]])

#### Slicing Rows and Columns

In [4]:
slice_row = arr1[0]
slice_row

array([0.41560478, 0.7699988 , 0.64323857])

In [7]:
slice_col = arr1[:, 0]
slice_col

array([0.41560478, 0.92447719, 0.53524803, 0.89207446])

In [8]:
slice3 = arr1[1:, :2]
slice3

array([[0.92447719, 0.83659771],
       [0.53524803, 0.23581939],
       [0.89207446, 0.28165516]])

### Creating Three-dimensional array.

In [10]:
arr3d = np.random.rand(3, 3)
arr3d

array([[0.04635795, 0.0811213 , 0.74112676],
       [0.62543691, 0.12553781, 0.50747692],
       [0.21193692, 0.25936426, 0.82650547]])

In [11]:
arr3d

array([[0.04635795, 0.0811213 , 0.74112676],
       [0.62543691, 0.12553781, 0.50747692],
       [0.21193692, 0.25936426, 0.82650547]])

### Hourly Rainfall analysis II

In [12]:
rain_mm_by_hour_for_week = np.array([[0, 0, 0, 0, 0, 0, 0, 4, 2, 2, 4, 4, 0, 0, 0, 6, 0, 3, 6, 0, 0, 0, 3, 0],
                                     [6, 4, 0, 5, 7, 0, 0, 2, 4, 0, 0, 6, 4, 0, 0, 0, 2, 6, 0, 0, 1, 0, 7, 0],
                                     [0, 0, 6, 0, 0, 4, 0, 0, 7, 3, 4, 2, 2, 3, 6, 5, 3, 0, 0, 0, 0, 0, 5, 3],
               			             [3, 0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 5, 5, 1, 0, 0, 0, 6, 5, 6, 4, 0, 0],
       	                             [4, 2, 2, 0, 0, 0, 0, 6, 4, 0, 0, 0, 0, 5, 0, 0, 0, 2, 0, 5, 2, 0, 0, 2],
       	                             [0, 2, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 5, 0, 6, 0, 1, 0, 0, 0, 2, 0, 0, 0],
                               	     [0, 3, 5, 1, 7, 3, 0, 2, 4, 7, 0, 1, 3, 0, 4, 0, 0, 1, 0, 0, 0, 6, 4, 0]])

In [16]:
rain_mm_by_hour_for_week[0]

array([0, 0, 0, 0, 0, 0, 0, 4, 2, 2, 4, 4, 0, 0, 0, 6, 0, 3, 6, 0, 0, 0,
       3, 0])

In [17]:
rain_mm_by_hour_for_week[:, :3]

array([[0, 0, 0],
       [6, 4, 0],
       [0, 0, 6],
       [3, 0, 0],
       [4, 2, 2],
       [0, 2, 0],
       [0, 3, 5]])

### Average Rainfall

What is the mean amount of rainfall for the first 3 hours of each weekday in this week? (Round off the mean value to 2 decimal places.)

In [20]:
print(f"{(rain_mm_by_hour_for_week[:, :3]).mean():.2f}")

1.76


### Slice the Rain
Which line of code among the following would return the amount of rainfall for the last 2 hours of Thursday?

In [27]:
rain_mm_by_hour_for_week[3 , -2:]

array([0, 0])

In [28]:
rain_mm_by_hour_for_week[3 , 22:]

array([0, 0])

In [29]:
rain_mm_by_hour_for_week[3,-3:]

array([4, 0, 0])

In [30]:
rain_mm_by_hour_for_week[3,3:]

array([4, 0, 0, 0, 0, 0, 0, 1, 0, 5, 5, 1, 0, 0, 0, 6, 5, 6, 4, 0, 0])

### Hourly Rainfall Analysis III

In [31]:
rain_mm_by_hour_for_2weeks = np.array([[[0, 0, 0, 0, 0, 0, 0, 4, 2, 2, 4, 4, 0, 0, 0, 6, 0, 3, 6, 0, 0, 0, 3, 0],
                                      [6, 4, 0, 5, 7, 0, 0, 2, 4, 0, 0, 6, 4, 0, 0, 0, 2, 6, 0, 0, 1, 0, 7, 0],
                                      [0, 0, 6, 0, 0, 4, 0, 0, 7, 3, 4, 2, 2, 3, 6, 5, 3, 0, 0, 0, 0, 0, 5, 3],
                                      [3, 0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 5, 5, 1, 0, 0, 0, 6, 5, 6, 4, 0, 0],
                                      [4, 2, 2, 0, 0, 0, 0, 6, 4, 0, 0, 0, 0, 5, 0, 0, 0, 2, 0, 5, 2, 0, 0, 2],
                                      [0, 2, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 5, 0, 6, 0, 1, 0, 0, 0, 2, 0, 0, 0],
                                      [0, 3, 5, 1, 7, 3, 0, 2, 4, 7, 0, 1, 3, 0, 4, 0, 0, 1, 0, 0, 0, 6, 4, 0]],

                                     [[3, 1, 4, 2, 0, 0, 0, 3, 0, 0, 5, 0, 0, 5, 0, 0, 0, 3, 0, 0, 0, 4, 4, 6],
                                      [2, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 2, 1, 7, 6, 0, 0, 0, 0, 3, 0, 0, 0],
                                      [0, 0, 0, 1, 0, 2, 5, 1, 0, 0, 0, 2, 7, 0, 0, 0, 2, 0, 5, 4, 0, 1, 7, 4],
                                      [2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 3, 0, 0, 0, 2, 0, 0, 0, 2, 7],
                                      [3, 0, 4, 0, 0, 6, 0, 0, 0, 3, 7, 0, 0, 0, 5, 0, 0, 0, 0, 0, 3, 0, 5, 0],
                                      [0, 0, 3, 0, 0, 0, 5, 0, 2, 1, 0, 0, 0, 0, 5, 0, 0, 6, 0, 4, 0, 0, 1, 0],
                                      [0, 0, 0, 0, 0, 4, 4, 0, 0, 4, 6, 6, 4, 6, 0, 1, 5, 0, 0, 0, 2, 0, 3, 7]]])

In [33]:
week_1 = rain_mm_by_hour_for_2weeks[0]

In [34]:
week_2 = rain_mm_by_hour_for_2weeks[1]

In [36]:
week_2

array([[3, 1, 4, 2, 0, 0, 0, 3, 0, 0, 5, 0, 0, 5, 0, 0, 0, 3, 0, 0, 0, 4,
        4, 6],
       [2, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 2, 1, 7, 6, 0, 0, 0, 0, 3, 0,
        0, 0],
       [0, 0, 0, 1, 0, 2, 5, 1, 0, 0, 0, 2, 7, 0, 0, 0, 2, 0, 5, 4, 0, 1,
        7, 4],
       [2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 3, 0, 0, 0, 2, 0, 0, 0,
        2, 7],
       [3, 0, 4, 0, 0, 6, 0, 0, 0, 3, 7, 0, 0, 0, 5, 0, 0, 0, 0, 0, 3, 0,
        5, 0],
       [0, 0, 3, 0, 0, 0, 5, 0, 2, 1, 0, 0, 0, 0, 5, 0, 0, 6, 0, 4, 0, 0,
        1, 0],
       [0, 0, 0, 0, 0, 4, 4, 0, 0, 4, 6, 6, 4, 6, 0, 1, 5, 0, 0, 0, 2, 0,
        3, 7]])

How would you obtain the array that represents the amount of rainfall by hour on the 1st day of the 2nd week.

In [39]:
rain_mm_by_hour_for_2weeks[1, 0]

array([3, 1, 4, 2, 0, 0, 0, 3, 0, 0, 5, 0, 0, 5, 0, 0, 0, 3, 0, 0, 0, 4,
       4, 6])

### Correcting the Data

Later you discover it did not rain in the last hour of the day of the last day of the last week you have data for.
Correct the amount of rainfall for this hour by setting it to 0.

Then calculate the new mean amount of rainfall for 2 weeks.

In [43]:
rain_mm_by_hour_for_2weeks[-1, -1:, -1] = 0

In [46]:
print(f"{rain_mm_by_hour_for_2weeks.mean():.2f}")

1.61
