## Practice Problem

1. Print the second row
2. Print the first and third rows
3. PRint the middle three columns
4. Challenge: Starting with second column, print every other column.

In [1]:
import numpy as np

In [8]:
arr1 = np.array([np.arange(1, 4), np.arange(4, 7), np.arange(7, 10)])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr1[1]

array([4, 5, 6])

In [19]:
arr1[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
arr1[:, 1]

array([2, 5, 8])

In [23]:
arr1[:, 1::]

array([[2, 3],
       [5, 6],
       [8, 9]])