### Sorting Arrays

The `sort(array)` function returns a copy of a sorted array.

In [1]:
import numpy as np

In [2]:
arr1 = np.random.rand(5)
arr1

array([0.29918866, 0.12762835, 0.01424428, 0.62091425, 0.57145355])

In [5]:
arr2 = np.sort(arr1)

In [6]:
arr2

array([0.01424428, 0.12762835, 0.29918866, 0.57145355, 0.62091425])

In [7]:
arr4 = np.random.rand(5)
arr4

array([0.21742185, 0.78269812, 0.96030335, 0.74545742, 0.00435092])

In [8]:
arr4.argsort()

array([4, 0, 3, 1, 2], dtype=int64)

In [9]:
rain_mm_by_hour_for_2weeks = np.array([[[0, 0, 0, 0, 0, 0, 0, 4, 2, 2, 4, 4, 0, 0, 0, 6, 0, 3, 6, 0, 0, 0, 3, 0],
                                        [6, 4, 0, 5, 7, 0, 0, 2, 4, 0, 0, 6, 4, 0, 0, 0, 2, 6, 0, 0, 1, 0, 7, 0],
                                        [0, 0, 6, 0, 0, 4, 0, 0, 7, 3, 4, 2, 2, 3, 6, 5, 3, 0, 0, 0, 0, 0, 5, 3],
                                        [3, 0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 5, 5, 1, 0, 0, 0, 6, 5, 6, 4, 0, 0],
                                        [4, 2, 2, 0, 0, 0, 0, 6, 4, 0, 0, 0, 0, 5, 0, 0, 0, 2, 0, 5, 2, 0, 0, 2],
                                        [0, 2, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 5, 0, 6, 0, 1, 0, 0, 0, 2, 0, 0, 0],
                                        [0, 3, 5, 1, 7, 3, 0, 2, 4, 7, 0, 1, 3, 0, 4, 0, 0, 1, 0, 0, 0, 6, 4, 0]],

                                       [[3, 1, 4, 2, 0, 0, 0, 3, 0, 0, 5, 0, 0, 5, 0, 0, 0, 3, 0, 0, 0, 4, 4, 6],
                                        [2, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 2, 1, 7, 6, 0, 0, 0, 0, 3, 0, 0, 0],
                                        [0, 0, 0, 1, 0, 2, 5, 1, 0, 0, 0, 2, 7, 0, 0, 0, 2, 0, 5, 4, 0, 1, 7, 4],
                                        [2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 3, 0, 0, 0, 2, 0, 0, 0, 2, 7],
                                        [3, 0, 4, 0, 0, 6, 0, 0, 0, 3, 7, 0, 0, 0, 5, 0, 0, 0, 0, 0, 3, 0, 5, 0],
                                        [0, 0, 3, 0, 0, 0, 5, 0, 2, 1, 0, 0, 0, 0, 5, 0, 0, 6, 0, 4, 0, 0, 1, 0],
                                        [0, 0, 0, 0, 0, 4, 4, 0, 0, 4, 6, 6, 4, 6, 0, 1, 5, 0, 0, 0, 2, 0, 3, 0]]])

In [15]:
np.argsort(rain_mm_by_hour_for_2weeks[1, 3])

array([10, 19, 17, 16, 15, 13, 12, 20,  9, 21,  7,  6,  5,  4,  1,  8, 22,
        3,  2, 18,  0, 14, 11, 23], dtype=int64)