## Universal functions

A __universal function__ is a stanalone function that performs element-wise operations, using one or two arrays or array-like arguments. \
To use a universal function, the syntax is `np.function_name(array_name)`

In [8]:
import numpy as np

In [9]:
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
arr1

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131]])

In [11]:
np.sum(arr1)

27

In [12]:
np.mean(arr1)

4.5

In [13]:
arr2 = np.array([[2, 7]])
arr3 = np.array([[2, 2]])
np.greater(arr2, arr3)

array([[False,  True]])